### ISSUE TITLE
Values not in Pascal or Kelvin

### ISSUE THREAD

**Issue by oyve** [oehoe/signalk-raspberry-pi-bme680#5]
In SignalK the values are not displayed accordingly?

Temperature: Displayed as Celcius (not Kelvin)
Pressure: Displayed as hPa (not Pa)

AFAICS the plugin-code looks correct, is the error in SignalK and not the plugin? Any ideas?

![sigk_screenshot_pressure_and_temperature](https://user-images.githubusercontent.com/16225018/116251925-1b6e7700-a73d-11eb-94cb-0c337aaf37ed.png)

SignalK v1.39.0

**Comment by oyve** [comment]
Update: The version in NPM is older than the code in the repo - please make a new release

**Comment by tkurki** [comment]
@oehoe are you reading this?

One primary point in Signal K is that even if the SI units used can be awkward at times they are *consistent*. Your plugin as published in npm currently breaks this contract and others now need to add extra code to handle data from this plugin - exactly the kind of stuff that we are trying to avoid!

Please publish the code that seems to be already fixed in this repo in npm also.

**Comment by oehoe** [comment]
@tkurki It's a test signalk plugin (and my only) I've created a year ago. I figured everyone just used the code to their liking. I've published the updated code now to npm.

**Comment by tkurki** [comment]
Thanks! See, sharing it has brought a bit of value and maybe joy for others. And you got some support requests to deal with!

Sorry about my grandiose tone above.
